name: flutter_in_app_purchase_demo
description: In App Purchase Demo Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  onepref: ^0.0.13
  provider: ^6.0.5
  settings_ui: ^2.0.2
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  percent_indicator: ^4.2.3
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true
=======
  uses-material-design: true

>>>>>>> a630379a6b6d132a3c56b0970e2970c453612c63
