name: flutter_in_app_purchase_demo
description: In App Purchase Demo Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
<<<<<<< HEAD
  onepref: ^0.0.11
=======
  onepref: ^0.0.14
>>>>>>> a630379a6b6d132a3c56b0970e2970c453612c63

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true
=======
  uses-material-design: true

>>>>>>> a630379a6b6d132a3c56b0970e2970c453612c63
